version: '3'

x-airflow-common:
  &airflow-common
  platform: linux/amd64
  build:
    context: "."
    dockerfile: "Dockerfile.airflow"
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    PYTHONPATH: '/opt/airflow/dags:/opt/airflow/airflow.cfg'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./dags/config/airflow.cfg:/opt/airlfow/airflow.cfg
    - ./logs:/opt/airflow/logs
   # - ./plugins:/opt/airflow/plugins
  depends_on:
    - postgres

services:
# POSTGRES DB
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=airflow
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"

# AIRFLOW DB INIT
  airflow-init:
    << : *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - airflow users list || ( airflow db init &&
        airflow users create
          --role Admin
          --username admin
          --password admin
          --email admin@airflow.com
          --firstname admin
          --lastname admin )
    restart: on-failure

  # AIRFLOW SCHEDULER
  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: airflow scheduler
    hostname: airflow_scheduler
    environment:
      <<: *airflow-common-env
    restart: always

  # AIRFLOW WEBSERVER
  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: airflow webserver 
    ports:
      - 8091:8080
    restart: always
    environment:
      <<: *airflow-common-env